spring:
  profiles:
    active:
    - dev
---

server:
  port: 5001

feign:
  httpclient:
    enabled: true




eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      ,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-landcloud5001

spring:
  profiles: dev  #开发环境
  application:
    name: propertymanagement-landcloud-consumer
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
  cloud:
    loadbalancer:
      retry:
        enabled: true



info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
--- 
server:
  port: 5001

feign:
  httpclient:
    enabled: true




eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.3:7001/eureka/
#      ,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-landcloud5001
    prefer-ip-address: true

spring:
  profiles: test  #部署
  application:
    name: propertymanagement-landcloud-consumer
  redis:
    host: 172.18.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
  cloud:
    loadbalancer:
      retry:
        enabled: true



info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$