spring:
  profiles:
    active:
    - dev
---
server:
  port: 6501

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      ,http://eureka-7002:7002/eureka/,http://eureka-7003:7003/eureka/
  instance:
    instance-id: microservicecloud-complaint6501

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.scau.zifeng.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml                       # mapper映射文件

spring:
  profiles: dev  #开发环境
  application:
    name: propertymanagement-complaintcloud
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/complaintcloud?serverTimezone=GMT&allowMultiQueries=true&autoReconnect=true    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000




info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

--- 


server:
  port: 6501

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://172.18.0.3:7001/eureka/
#      ,http://eureka-7002:7002/eureka/,http://eureka-7003:7003/eureka/
  instance:
    instance-id: microservicecloud-complaint6501
    prefer-ip-address: true

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.scau.zifeng.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml                       # mapper映射文件

spring:
  profiles: test  #部署
  application:
    name: propertymanagement-complaintcloud
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://172.18.0.1:3306/complaintcloud?serverTimezone=GMT&allowMultiQueries=true&autoReconnect=true    # 数据库名称
    username: root
    password: Aini0825+
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


  redis:
    host: 172.18.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000




info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    